### PR TITLE
Upgrade to MobX v6

### LINKED ISSUE #32: Support mobx v6
When can you upgrade this library to support mobx v6?
Thanks to make awesome library.

### PR DESCRIPTION
**Pull request by jeffijoe**
Upgrades to the library to support MobX 6. We had to wrap the task in an `action` to prevent MobX from automatically converting it to an action.

**BREAKING CHANGE**: The decorator will break when a MobX decorator is used on the same method.

Closes #32

### CODE REVIEW

**Comment by kkollman** [comment]
@jeffijoe Awesome news! Does it work with mobx's `makeObservable` method?

**Comment by jeffijoe** [comment]
I am not sure since I haven't used it, but I don't see why not, try it out and let me know!

**Comment by kkollman** [comment]
Yeah, I checked it and unfortunately, it doesn't - mobx throws an `Invalid annotation` error. If I find any solution, I'll post it here

**Comment by jeffijoe** [comment]
My recommendation is to use property initializers like this:

```js
class MyClass {
  myTask = task(async () => ...)
}
```

**Comment by kkollman** [comment]
Thanks you, that is what I'll do!

**Pull request merged**
